repos:
  - repo: local
    hooks:
      - id: requirements
        name: requirements
        language: system
        pass_filenames: False
        entry: bash -c 'venv/bin/pip3 freeze > requirements.txt; git add requirements.txt'
        stage: [commit]