
version: '3.1'



services:
  app:
    build: .
    ports:
      - "8080:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_PORT=3306               
      - DB_USER=root                  
      - DB_PASSWORD=password          


  redis:
    image: redis:alpine
    ports:
      - "6380:6379"

  db:
    image: mysql 
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: